In [18]:
import numpy as np

long_vector = int(input("Indica el la longitud de tu array"))

vector = np.ones(long_vector)



In [19]:
filas = int(input("Pon las filas:"))
columnas = int(input("Pon las columnas:"))


if filas*columnas == long_vector:
    vector = np.reshape(vector, (filas, columnas))
else:
    print("no se puede realizar")

In [20]:
identidad = np.eye(filas,columnas)

In [21]:
print(vector)
print(identidad)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
