In [20]:
import numpy as np

# Array 1d 8 elementos = 0
array_1 = np.zeros(8)

# Cambiar los elementos a 2
array_1[:]= 2

In [21]:
print(array_1)

[2. 2. 2. 2. 2. 2. 2. 2.]


In [29]:
import numpy as np
# Array con número pares del 1 al 10
array_2 = np.arange(2,11,2)

# 4. Sumar números usando bucle y método
suma_bucle = 0 

for i in array_2:
    suma_bucle = suma_bucle + i
suma_np = np.sum(array_2)

# 5. Revertir array 2 y guardarlo en una variable independiente
    # El [:] es para que sean independientes
array_2_revertido = array_2[::-1].copy()

array_2_revertido[:] = 0



In [30]:
print(array_2)
print(f"Con el bucle el resultado es: {suma_bucle}")
print(f"Con el método el resultado es: {suma_np}")
print(array_2_revertido)

[ 2  4  6  8 10]
Con el bucle el resultado es: 30
Con el método el resultado es: 30
[0 0 0 0 0]


In [24]:
# Elementos comunes entre array_1 y array_2

array_intersect = np.intersect1d(array_1, array_2)
array_intersect_2 = np.intersect1d(array_2_revertido, array_2)

In [25]:
print(array_intersect)
print(array_intersect_2)

[2.]
[ 2  4  6  8 10]


In [26]:
long_a3 = int(input("Indica el la longitud de tu array"))

array_3 = np.ones(long_a3)
print(array_3)

[1. 1. 1. 1. 1.]
