In [ ]:
import numpy as np


para ver la version del paquete:
conda search numpy --info 

1- Crear un array de dimension 8 con 8 ceros:

In [ ]:
import numpy as np
array_vacio=np.zeros((1,8)) #tambien valdria np.zeros(8)
print(array_vacio)

2. Haz que todos los elementos de este array sean igual a 2 
Se puede reasignar con: 
array_vacio[array_vacio == 0] = 2 , sustituye los elementos que valen 0 de cualquier valor del array.
array_vacío[x:,y:] = 2 , sustituye todos los valores desde la fila x y desde la columna y.

In [ ]:
import numpy as np
array_vacio=np.zeros((1,8))
#array_vacio[array_vacio ==0]=2 -> Funciona
array_vacio[0:]=2 #tambien funciona
print(array_vacio)

3.Crea un array_2 que contenga todos los números pares del 1 al 10.


In [ ]:
import numpy as np
array_pares =np.arange(2,11,2)
print(array_pares)
print(type(array_pares))

4.Suma todos los elementos del array_2 usando un bucle y después usando un método
de numpy. Compara los resultados

In [ ]:
import numpy as np
array_pares =np.arange(2,11,2)
suma=0
for i in array_pares:
    suma+=i
print(suma)
suma_array=array_pares.sum()
print(suma_array)

5. Revierte array_2 y guárdalo en una variable independiente. 

In [1]:
import numpy as np
array_pares =np.arange(2,11,2)
array_invertido=np.arange(5)

print(array_invertido)
#El [:] crea una copia, pero necesitas inicializarlo o bien con np.arrange(misma dimension que el que quieres copiar, en este caso manualmente).
#De forma generica se hace
#array_invertido=np.empty_like(array_pares, dtype=int)-> dtype opcional
array_invertido[:]= array_pares[::-1]
print(array_pares)
print(array_invertido)


[0 1 2 3 4]
[ 2  4  6  8 10]
[10  8  6  4  2]


6. Encuentra los elementos comunes entre array_1 y array_2 y entre array_2 y
array_2_revertido
 (Pista: Investiga el uso de intersect1d() de numpy)

In [ ]:
import numpy as np
array_vacio=np.zeros((1,8))
array_vacio[0:]=2 
array_pares =np.arange(2,11,2)
#El [:] crea una copia.
array_invertido[:]= array_pares[::-1]
interseccion_1= np.intersect1d(array_vacio,array_pares)
print(interseccion_1)

7. Crea un arrays lleno de 1s con una longitud dada por el usuario

In [ ]:
import numpy as np
x = int(input('De que longitud quieres crear tu matriz de 1s?'))
array_unos = np.ones((x))
print(array_unos)

Parte 2

1. Crea un array con 15 números enteros aleatorios entre 1 y 100

In [ ]:
import numpy as np
array_aleatorio = np.random.randint(1,101, size=15)
print(array_aleatorio)

2. Multiplica todos los elementos del array usando un bucle y después usando un
método de numpy. Compara los resultados

In [ ]:
import numpy as np
array_aleatorio = np.random.randint(1,101, size=15)
multi = 1
for i in array_aleatorio:
    multi*= i
multi_array = array_aleatorio.prod()
print(multi, multi_array)
print(array_aleatorio)
#Da un error de que excede el limite de memoria : /var/folders/vj/kdbk1dbx3jb0m3cypnqd4sjc0000gp/T/ipykernel_42257/1832981948.py:5: RuntimeWarning: overflow encountered in long_scalars
  #multi*= i

3. Crea otro array con 15 números decimales aleatorios entre 0 y 1

In [ ]:
import numpy as np
array_aleatorio_2 = np.random.random(15)
print(array_aleatorio_2)

4. Suma los elementos de ambos arrays elementos por elemento. Resuélvelo usando un
operador y después con una función de numpy
 (Pista: busca en google que función de numpy hace esto)

In [ ]:
import numpy as np
array_aleatorio = np.random.randint(1,101, size=15)
array_aleatorio_2 = np.random.random(15)
print(array_aleatorio)
print(array_aleatorio_2)
suma_op= array_aleatorio + array_aleatorio_2
print(suma_op) 
#funcion numpy
suma_numpy = np.add(array_aleatorio,array_aleatorio_2)
print(suma_numpy)

5. Ahora réstalos. Resuélvelo usando un operador y después con una función de numpy
(Pista: busca en google que función de numpy hace esto)

In [ ]:
resta_op= array_aleatorio - array_aleatorio_2
print(resta_op) 
#funcion numpy
resta_numpy = np.subtract(array_aleatorio,array_aleatorio_2)
print(resta_numpy)

6. Haz lo mismo con la multiplicación elemento por elemento. Usa un operador y
después con una función de numpy
 (Pista: busca en google que función de numpy hace esto)

In [ ]:
multi_op= array_aleatorio * array_aleatorio_2
print(multi_op) 
#funcion numpy
multi_numpy = np.multiply(array_aleatorio,array_aleatorio_2)
print(multi_numpy)

7. Encuentra el valor más alto del primer array que has creado. 

In [ ]:
num_alto=np.max(array_aleatorio)
print(num_alto)

8. Calcula la media (mean), la mediana (median) y al deviación estandar (standard
deviation) de los arrays (Nota: No nos importa el significado matemático de estos
valores, lo importante es que encuentres que función de numpy necesitas. Puedes
hacer la búsqueda en castellano o en inglés, aunque en inglés muchas veces suele
haber más resultados).

In [ ]:
media= np.mean(array_aleatorio)
print(media)
mediana=np.median(array_aleatorio)
print(mediana)

9. Crea un arrays lleno de 1s con una longitud dada por el usuario

In [ ]:
import numpy as np
x = int(input('De que longitud quieres crear tu matriz de 1s?'))
array_unos = np.ones((x))
print(array_unos)

10.Cambia la forma del array para que tenga una estructura de tipo (filas, columnas)

In [ ]:
nuevo_array=array_unos.reshape(2,4)
print(nuevo_array)

11.Crea una “matriz identidad” con la misma forma que el array anterior (filas, columnas)

In [ ]:
ident_array=np.eye(2,4)
print(ident_array)

12.Concatena ambas estructuras horizontalmente y verticalmente
 (Pista: Investiga el funcionamiento de concatenate() y de vstack() y hstack() de numpy)

In [ ]:
horiz_array=np.concatenate(ident_array)
print(horiz_array)
ver1_array=np.vstack(ident_array)
print(ver1_array)
ver2_array=np.hstack(ident_array)
print(ver2_array)